name: Server

on:
  push:
    paths: ['server/**', '.github/workflows/server.yml']

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Build
      working-directory: server
      run: go build -o server -v main.go
      
    - uses: actions/upload-artifact@v2
      with:
        name: server-${{ matrix.os }}
        path: server/server*

